### ISSUE TITLE
Re-transmission algorithm for sequencer

### ISSUE THREAD

**Issue by jeremy-melnyk** [jeremy091/SOEN423_Project#18]
If a packet is identified as lost, it must be re-transmitted to the appropriate replica without being added to the operation log.

**Comment by tv14** [comment]
Using reliable multicast, this is not an issue. My sequencer sends the multicast to all replicas. These replicas then resend to all other replicas. Thus will be multiple duplicates of the same packet being received. Thus losing a packet is not a big deal since there are other duplicate packets being received.

If a replica successfully receives duplicate packets it ignores the new duplicates.

Reference: Group communication page 8
